const authRoutes = require("./auth.routes");
const addressRoutes = require("./address.routes");
const socialMediaRoutes = require("./socialmedia.routes");
const usersRoutes = require("./users.routes");
const searchRoutes = require("./search.routes");
const stripeRoutes = require("./stripe.routes");
const annualFeeAdminRoutes = require("./annualFeeAdmin.routes");
const publicPricingRoutes = require("./publicPricing.routes");
const roleRoutes = require("./roles.routes");
const legalDocumentsRoutes = require("./legalDocuments.routes");
const profileRoutes = require("./profile.routes");
const categoryRoutes = require("./category.routes");
const socialMediaPublicRoutes = require("./socialmediaPublic.routes");
const portfolioRoutes = require("./portfolio.routes");
const couponRoutes = require("./coupon.routes");
const itensRoutes = require("./itens.routes");
const checkoutRoutes = require("./checkout.routes");
const orderRoutes = require("./order.routes");
const affiliateRoutes = require("./affiliate.routes");
const affiliateAdminRoutes = require("./affiliateAdmin.routes");
const enxameRoutes = require("./enxame.routes");
const enxameAdminRoutes = require("./enxameAdmin.routes");
const couponAdminRoutes = require("./couponAdmin.routes");
const adminUsersRoutes = require("./adminUsers.routes");
const bookingRoutes = require("./booking.routes");
const bookingPublicRoutes = require("./bookingPublic.routes");
const profilePublicRoutes = require("./profilePublic.routes");
const portfolioPublicRoutes = require("./portfolioPublic.routes");
const profileServiceRoutes = require("./profileService.routes");
const profileServicePublicRoutes = require("./profileServicePublic.routes");
const profileProductRoutes = require("./profileProduct.routes");
const profileProductPublicRoutes = require("./profileProductPublic.routes");
const profileProductOrderRoutes = require("./profileProductOrder.routes");
const rankingRoutes = require("./ranking.routes");
const adminRankingRoutes = require("./adminRanking.routes");
const clanRoutes = require("./clan.routes");
const clanPublicRoutes = require("./clanPublic.routes");
const bookingFeeAdminRoutes = require("./bookingFeeAdmin.routes");
const bookingFeePublicRoutes = require("./bookingFeePublic.routes");
const serviceRequestRoutes = require("./serviceRequest.routes");
const portfolioFeedRoutes = require("./portfolioFeed.routes");
const entityFollowRoutes = require("./entityFollow.routes");
const conversationRoutes = require("./conversation.routes");
const adminXpRoutes = require("./adminXp.routes");
const xpRoutes = require("./xp.routes");
const engagementRoutes = require("./engagement.routes");
const polenRoutes = require("./polen.routes");
const adminPolenRoutes = require("./adminPolen.routes");
const manifestationRoutes = require("./manifestation.routes");
const manifestationAdminRoutes = require("./manifestationAdmin.routes");
const liveAdminRoutes = require("./liveAdmin.routes");
const liveRoutes = require("./live.routes");
const polenProductsRoutes = require("./polenProducts.routes");
const polenProductsAdminRoutes = require("./polenProductsAdmin.routes");
const premiumRoutes = require("./premium.routes");
const premiumAdminRoutes = require("./premiumAdmin.routes");
const coursesRoutes = require("./courses.routes");
const coursesPublicRoutes = require("./coursesPublic.routes");
const onboardingRoutes = require("./onboarding.routes");
const userAccountPortfolioRoutes = require("./userAccountPortfolio.routes");
const userPublicRoutes = require("./userPublic.routes");
const portfolioCommentRoutes = require("./portfolioComment.routes");
const storyRoutes = require("./storyRoutes");
const storyPublicRoutes = require("./storyPublicRoutes");
const notificationRoutes = require("./notificationRoutes");
const chatRoutes = require("./chatRoutes");
const supervisionRoutes = require("./supervision.routes");
const sellerBalanceRoutes = require("./sellerBalance.routes");
const chatModerationAdminRoutes = require("./chatModerationAdmin.routes");
const bookingPayoutRoutes = require("./bookingPayout.routes");
const productCategoryRoutes = require("./productCategory.routes");
const productCategoryAdminRoutes = require("./productCategoryAdmin.routes");
const productRequestRoutes = require("./productRequest.routes");
const courseRequestRoutes = require("./courseRequest.routes");
const storeModerationAdminRoutes = require("./storeModerationAdmin.routes");
const storePricePreviewRoutes = require("./storePricePreview.routes");
const bookmarkRoutes = require("./bookmark.routes");
const consentRoutes = require("./consent.routes");
const siteAssetRoutes = require("./siteAsset.routes");
const siteAssetAdminRoutes = require("./siteAssetAdmin.routes");
const siteTextRoutes = require("./siteText.routes");
const siteTextAdminRoutes = require("./siteTextAdmin.routes");
const earningsRoutes = require("./earnings.routes");
const postReportsRoutes = require("./postReports.routes");
const countriesRoutes = require("./countries.routes");
const regionRoutes = require("./region.routes");
const navCountsRoutes = require("./navCounts.routes");
const userTourProgressRoutes = require("./userTourProgress.routes");
const meOfferingsRoutes = require("./meOfferings.routes");
const monetizationIntentRoutes = require("./monetizationIntent.routes");
const audioLibraryRoutes = require("./audioLibrary.routes");
const audioLibraryAdminRoutes = require("./audioLibraryAdmin.routes");
const casaPublicRoutes = require("./casaPublic.routes");
const casaAdminRoutes = require("./casaAdmin.routes");
const blogRoutes = require("./blog.routes");
const blogAdminRoutes = require("./blogAdmin.routes");
const architectureAdminRoutes = require("./architectureAdmin.routes");
const marketRoutes = require("./market.routes");
const walletFinanceRoutes = require("./walletFinance.routes");
const paymentOpsRoutes = require("./paymentOps.routes");

module.exports = (app) => {
  app.get("/health", (req, res) => {
    res.json({ status: "ok" });
  });

  app.use("/auth", authRoutes);
  app.use("/address", addressRoutes);
  app.use("/users", usersRoutes);
  app.use("/stripe", stripeRoutes);
  app.use("/admin/annual-fee", annualFeeAdminRoutes);
  app.use("/public", publicPricingRoutes);
  app.use("/search", searchRoutes);
  app.use("/role", roleRoutes);
  app.use("/legalDocuments", legalDocumentsRoutes);
  app.use("/profile", profileRoutes);
  app.use("/profile/:id_profile/social-media", socialMediaRoutes);
  app.use("/profile/:id_profile/portfolio", portfolioRoutes);
  app.use("/categories", categoryRoutes);
  app.use("/social-media", socialMediaPublicRoutes);
  app.use("/coupon", couponRoutes);
  app.use("/itens", itensRoutes);
  app.use("/checkout", checkoutRoutes);
  app.use("/order", orderRoutes);
  app.use("/me/affiliate", affiliateRoutes);
  app.use("/admin/affiliate", affiliateAdminRoutes);
  app.use("/enxames", enxameRoutes);
  app.use("/admin", enxameAdminRoutes);
  app.use("/admin/coupons", couponAdminRoutes);
  app.use("/admin", adminUsersRoutes);
  app.use("/profile", bookingRoutes);
  app.use("/profile/:id_profile/services", profileServiceRoutes);
  app.use("/profile/:id_profile/products", profileProductRoutes);
  app.use("/me", profileProductOrderRoutes);
  app.use("/public/profile", bookingPublicRoutes);
  app.use("/public/profile", profileServicePublicRoutes);
  app.use("/public/profile", profileProductPublicRoutes);
  app.use("/public/creator", profilePublicRoutes);
  app.use("/public", portfolioPublicRoutes);
  app.use("/ranking", rankingRoutes);
  app.use("/admin", adminRankingRoutes);
  app.use("/clans", clanRoutes);
  app.use("/public/clans", clanPublicRoutes);
  app.use("/admin/booking-fees", bookingFeeAdminRoutes);
  app.use("/public/booking-fees", bookingFeePublicRoutes);
  app.use("/service-requests", serviceRequestRoutes);
  app.use("/feed", portfolioFeedRoutes);
  app.use("/entity-follows", entityFollowRoutes);
  app.use("/conversations", conversationRoutes);
  app.use("/admin", adminXpRoutes);
  app.use("/subprofiles", xpRoutes);
  app.use("/polens", polenRoutes);
  app.use("/admin/polens", adminPolenRoutes);
  app.use("/manifestations", manifestationRoutes);
  app.use("/admin/manifestations", manifestationAdminRoutes);
  app.use("/admin/lives", liveAdminRoutes);
  app.use("/lives", liveRoutes);
  app.use("/polens", polenProductsRoutes);
  app.use("/admin/polens", polenProductsAdminRoutes);
  app.use("/premium", premiumRoutes);
  app.use("/admin/premium", premiumAdminRoutes);
  app.use("/me/courses", coursesRoutes);
  app.use("/courses", coursesPublicRoutes);
  app.use("/me/portfolio", userAccountPortfolioRoutes);
  app.use("/public/users", userPublicRoutes);
  app.use("/portfolio", portfolioCommentRoutes);
  app.use("/me/stories", storyRoutes);
  app.use("/stories", storyPublicRoutes);
  app.use("/me/notifications", notificationRoutes);
  app.use("/me/engagement", engagementRoutes);
  app.use("/chat", chatRoutes);
  app.use("/supervision", supervisionRoutes);
  app.use("/me/onboarding", onboardingRoutes);
  app.use("/", sellerBalanceRoutes);
  app.use("/admin", chatModerationAdminRoutes);
  app.use("/", bookingPayoutRoutes);
  app.use("/product-categories", productCategoryRoutes);
  app.use("/admin/store/product-categories", productCategoryAdminRoutes);
  app.use("/product-requests", productRequestRoutes);
  app.use("/course-requests", courseRequestRoutes);
  app.use("/admin/store", storeModerationAdminRoutes);
  app.use("/store", storePricePreviewRoutes);
  app.use("/me/bookmarks", bookmarkRoutes);
  app.use("/me/consents", consentRoutes);
  app.use("/site-assets", siteAssetRoutes);
  app.use("/admin/site-assets", siteAssetAdminRoutes);
  app.use("/site-texts", siteTextRoutes);
  app.use("/admin/site-texts", siteTextAdminRoutes);
  app.use("/", earningsRoutes);
  app.use("/", postReportsRoutes);
  app.use("/countries", countriesRoutes);
  app.use("/regions", regionRoutes);
  app.use("/me", navCountsRoutes);
  app.use("/tours", userTourProgressRoutes);
  app.use("/me", meOfferingsRoutes);
  app.use("/onboarding/intent", monetizationIntentRoutes);
  app.use("/audio-library", audioLibraryRoutes);
  app.use("/admin/audio-library", audioLibraryAdminRoutes);
  app.use("/casa", casaPublicRoutes);
  app.use("/admin/casa", casaAdminRoutes);
  app.use("/blog", blogRoutes);
  app.use("/", marketRoutes);
  app.use("/", walletFinanceRoutes);
  app.use("/admin/blog", blogAdminRoutes);
  app.use("/admin/architecture", architectureAdminRoutes);
  app.use("/", paymentOpsRoutes);
};
